/// Flutter icons Blooddrop
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Blooddrop
///      fonts:
///       - asset: fonts/Blooddrop.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Blooddrop {
  Blooddrop._();

  static const _kFontFam = 'Blooddrop';
  static const String? _kFontPkg = null;

  static const IconData blood_drop = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
