/// Flutter icons HidePassword
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HidePassword
///      fonts:
///       - asset: fonts/HidePassword.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HidePassword {
  HidePassword._();

  static const _kFontFam = 'HidePassword';
  static const String? _kFontPkg = null;

  static const IconData hide_password = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
