/// Flutter icons Verified
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Verified
///      fonts:
///       - asset: fonts/Verified.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Verified {
  Verified._();

  static const _kFontFam = 'Verified';
  static const String? _kFontPkg = null;

  static const IconData icons8_verified_account_100 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
